default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gallery_service
  password: your_mysql_password
  host: db

development:
  <<: *default
  database: gallery_service_development
  host: db

test:
  <<: *default
  database: gallery_service_test
  host: db

production:
  <<: *default
  database: gallery_service_production
  username: gallery_service
  password: <%= ENV['GALLERY_SERVICE_DATABASE_PASSWORD'] %>
  host: db
  